### ISSUE TITLE
how to determine board id and card id

### ISSUE THREAD

**Issue by matthewchung74** [olebedev/hook-to-trello#3]
Thank you for sharing this. A bit of a silly question, when I look at the Trello URLs, for a board I have something like this:
https://trello.com/b/7bhIklbf/matt-pre-sprint-task
and for a card
https://trello.com/c/eSX3T3TX/4-1-first-fake-app-based-on-current-wordbug

Am I correct in assuming the board id is 7bhIklbf and the card id is eSX3T3TX ? 

I'm asking because I'm not seeing my updates, even though I am seeing requests come in/out
Listening 5000 port...
GET //b/
POST //b/7bhIklbf

Thank you very much.

**Comment by olebedev** [comment]
Sorry for delay, I had no time to write the answer. 
When I wrote this app trello shares own IDs to UX explicitly. So now I have no clue how to get board's and card's IDs from UI. =) I think there is some possibility to get IDs via json api.
Could you send an answer if you find it, please. Thanks!

**Comment by matthewchung74** [comment]
I also have no idea. I believe zapier is having the same issue.

On Sunday, March 1, 2015, Oleg Lebedev notifications@github.com wrote:

> Sorry for delay, I had no time to write the answer.
> When I wrote this app trello shares own IDs to UX explicitly. So now I
> have no clue how to get board's and card's IDs from UI. =) I think there is
> some possibility to get IDs via json api.
> Could you send an answer if you find it, please. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/olebedev/hook-to-trello/issues/3#issuecomment-76611849
> .

## 

Regards,
Matt

**Comment by olebedev** [comment]
A quick  trello json api overview clarified the things. 
Board ID you can grab via [this](https://trello.com/docs/api/member/index.html#get-1-members-idmember-or-username-boards) GET method. And cards IDs you can grub via [this](https://trello.com/docs/api/board/index.html#get-1-boards-board-id-cards) one.
=)
